### ISSUE TITLE
 No module named 'externals.efm_datasets.efm_datasets.dataloaders.DDADDataset'

### ISSUE THREAD

**Issue by JOP-Lee** [SysCV/r3d3#2]
Thank you for your work. I have encountered the following problems. It seems that the DDADDataset.py file is missing in the efm_datasets folder.

**Comment by AronDiSc** [comment]
Hi @JOP-Lee. Thank you for your interest. May I ask you how you've encountered this problem? Because we are not making use of the [EFM-Datasets repository](https://github.com/TRI-ML/efm_datasets).

**Comment by JOP-Lee** [comment]
@AronDiSc 
Dgp also encountered the same problem and could not be installed in the following ways.
pip install git+https://github.com/TRI-ML/dgp.git@v1.5

**Comment by AronDiSc** [comment]
@JOP-Lee I'm glad that you could solve the problem. We use a fork of the vidar module located at [https://github.com/AronDiSc/vidar](https://github.com/AronDiSc/vidar) which is from an older state and has a few modifications. I guess this is why the problem occurred.
